### PR TITLE
Friendship

### PR DESCRIPTION
**Pull request by layzrd**
features enable to create friendship within users

    user can invite another user

    invited user able to accept/reject the invitation

    user can cancel the invitation

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @abredi 
### You did well :clap: However, you have a few issues to address:-
- [ ] Write unit tests for the projects
- [ ] I am having trouble running the app, it outputs an error
error
- [ ] Use Postgres as a database for this project
### Make the changes and submit for another review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Require Change :red_circle: 
### Great work! 
I got no errors, your project looks clean as far as now. __But__ as my previous college state, you most use PostgreSql (__`gem 'pg'`__) for this project. make sure you migrate from SqlLite3 to PostgreSql and submit for approval 
# :computer: Happy Coding :computer: :nerd_face:

**Comment by layzrd** [comment]
Hello, @Dandush03, can you please explain why I should use PostgreSQL instead of SQLite for development?
I didn't get any instruction to do that, and as far as I know, it's preferable to use SQLite in development. FYI I used PostgreSQL for production.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the job done so far and for applying the suggested changes
However, there are still some missing requirements

1. According to the usage of PostgreSQL kindly read [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone2/postgre.png). Kindly PostgreSQL in development environment, please

2. Posts timeline includes posts written by logged-in user and their friends, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) . It's not what is done in your application. Kindly fix that.

3. Also, it looks like the Github's actions workflows for linters is not enable. Kindly do it.

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Great job :+1: :100: :clap: thanks for making the required changes.

Well done, your project is approved now you can merge to develop

## Happy Coding :tophat:

**Pull request merged**
